#!/bin/bash

set -e

pushd "$(dirname $0)/.."

mkdir -p bin

[ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"

CGO_ENABLED=0 GOARCH=amd64 go build -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o bin/packer-plugin-harvester-amd64
